### ISSUE TITLE
"Error [ERR_REQUIRE_ESM]: require() " reported from duh-ipxact

### ISSUE THREAD

**Issue by xiaoweish** [sifive/duh-ipxact#11]
Hi Aliaksei ,

Thanks for your dut-* related tools, and I'm trying it to conver IP-XACT to DUH in my local, however there is below error. Would you please help have a lookt at it? Thanks

Step 1,
Downloaded https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz, and unpack it in my home directory, and set below in my terminal

`export PATH=/home/cad/node-v16.17.0-linux-x64/bin:$PATH
`
Step 2,
hit below command to install duh-ipxact

`npm i -g duh-ipxact
`
Step 3,
Use this ip-xact as an example to convert it to DUH format, https://github.com/klauspetersen/ipxact/blob/master/example/axi_motor_v2_00_a.xml

`npx duh-ipxact ipxact2duh axi_motor_v2_00_a.xml axi_motor_v2_00_a.json5
`

And now there is below errors:
```
$ npx duh-ipxact ipxact2duh axi_motor_v2_00_a.xml axi_motor_v2_00_a.json5
/home/cad/node-v16.17.0-linux-x64/lib/node_modules/duh-ipxact/bin/duh-ipxact.js:8
const fetch = require('node-fetch');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/cad/node-v16.17.0-linux-x64/lib/node_modules/duh-ipxact/node_modules/node-fetch/src/index.js from /home/cad/node-v16.17.0-linux-x64/lib/node_modules/duh-ipxact/bin/duh-ipxact.js not supported.
Instead change the require of index.js in /home/cad/node-v16.17.0-linux-x64/lib/node_modules/duh-ipxact/bin/duh-ipxact.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/cad/node-v16.17.0-linux-x64/lib/node_modules/duh-ipxact/bin/duh-ipxact.js:8:15) {
  code: 'ERR_REQUIRE_ESM'
}
```

I've got below page,
https://stackoverflow.com/questions/69087292/requirenode-fetch-gives-err-require-esm

it says,

> If you want to require it, then downgrade to v2.

However, in package.json the dependencies part includes:
`	"node-fetch": "^3.2.8", 
`
So, do I miss something in my local?

Thanks Aliaksei very much!

**Comment by drom** [comment]
@arvalid is it still an issue with the latest version?
