### ISSUE TITLE
duh2ipxact crashes when running on xml generated by coreConsultant for DW_APB_I2C of Synopsys

### ISSUE THREAD

**Issue by Ramlakshmi3733** [sifive/duh-ipxact#4]
i have placed the files in block-id2silicon-firstsketch/garbage/i2c folder in github
the xml in the dw_apb_i2c_firstsketch/export directory.

**Comment by drom** [comment]
fixed in v0.7.3
https://github.com/sifive/duh-ipxact/commit/77c2513a23ece4b253b75ff5bcd4388ba8d84a72
